# -*- coding: utf-8 -*-

import os
import json
import re
import torch
from tqdm import tqdm
from transformers import pipeline
from pydantic import BaseModel, Field
from dotenv import load_dotenv

# ==============================================================================
# PYDANTIC SCHEMA
# ==============================================================================
class Entity(BaseModel):
    name: str = Field(description="The exact text span of the entity from the abstract.")
    type: str = Field(description="The classification category of the entity.")

class PaperResult(BaseModel):
    paper_id: str = Field(description="The ID of the paper provided in the prompt.")
    entities: list[Entity]

class BatchNERResult(BaseModel):
    results: list[PaperResult]

# ==============================================================================
# CONFIGURATION
# ==============================================================================
CONFIG = {
    "INPUT_FILE": "./data/balanced_papers_2025.json",
    "OUTPUT_FILE": "./data/hf_llama_NER_annotated_balanced_papers_2025.json",
    "MODEL_NAME": "meta-llama/Llama-3.1-8B-Instruct", 
    "BATCH_SIZE": 1, # Sequential processing avoids padding alignment issues
    
    "ENTITY_DEFINITIONS": {
        "Task": "Applications, goals, or broader fields of study.",
        "Model": "Specific, named architectures or systems.",
        "Algorithm": "Theoretical methods, techniques, or general architecture families.",
        "Dataset": "Named data collections or benchmarks.",
        "Metric": "Performance measures or evaluation standards.",
        "Hardware": "Physical compute resources or chips."
    }
}

def generate_prompt(paper_id, abstract_text):
    definitions = "\n".join([f"- {k}: {v}" for k, v in CONFIG['ENTITY_DEFINITIONS'].items()])
    schema_json = json.dumps(BatchNERResult.model_json_schema(), indent=2)

    prompt = f"""
You are an expert AI researcher performing NER.
Extract all scientific entities from the abstract below and classify them into these specific types:

{definitions}

Rules:
1. Extract the EXACT text span as it appears in the abstract.
2. Do not infer entities that are not explicitly written.
3. Ensure the Paper ID provided below is included in your JSON response.

You MUST respond strictly matching the following JSON schema. Do NOT wrap your response in markdown or add explanations. Just output valid JSON:
{schema_json}

--- PAPER ID: {paper_id} ---
{abstract_text}
"""
    return prompt

def extract_json_from_text(text):
    """Robust parser to handle markdown blocks frequently generated by open-weight models."""
    # Attempt to find JSON wrapped in markdown code blocks. 
    # Using `{3}` prevents the markdown parser from prematurely closing the code block.
    pattern = r"`{3}(?:json)?\s*(\{.*?\})\s*`{3}"
    match = re.search(pattern, text, re.DOTALL)
    if match:
        return match.group(1)
    
    # Fallback: extract substring between the first { and last }
    start = text.find('{')
    end = text.rfind('}')
    if start != -1 and end != -1:
        return text[start:end+1]
    
    return text

def main():
    # Load environment variables
    load_dotenv()
    
    # Try fetching standard token variable names
    raw_token = os.environ.get('HF_TOKEN') or os.environ.get('HUGGING_FACE_HUB_TOKEN')
    
    if raw_token:
        # Strip literal outer quotes and whitespace to avoid 401 from malformed values
        hf_token = raw_token.strip("'\" \t")
        
        # Mask the token for safety while confirming it is successfully loaded
        masked_token = f"{hf_token[:7]}...{hf_token[-5:]}" if len(hf_token) > 12 else "loaded but short"
        print(f"🔑 Successfully loaded and sanitized HF_TOKEN: {masked_token}")
        
        # Inject directly into the process environment variables to guarantee sub-modules find it
        os.environ["HF_TOKEN"] = hf_token
        os.environ["HUGGING_FACE_HUB_TOKEN"] = hf_token
    else:
        hf_token = None
        print("⚠️ Warning: No HF_TOKEN or HUGGING_FACE_HUB_TOKEN found in your environmental variables.")
        print("If your .env is in a parent directory, you may need to move it to the current folder or specify its path.")

    if not os.path.exists(CONFIG['INPUT_FILE']):
        print(f"❌ Input file not found: {CONFIG['INPUT_FILE']}")
        return

    with open(CONFIG['INPUT_FILE'], 'r', encoding='utf-8') as f:
        papers = json.load(f)

    annotated_papers = {}
    if os.path.exists(CONFIG['OUTPUT_FILE']):
        with open(CONFIG['OUTPUT_FILE'], 'r', encoding='utf-8') as f:
            annotated_papers = json.load(f)

    papers_to_process = {pid: p for pid, p in papers.items() if pid not in annotated_papers}
    if not papers_to_process:
        print("✅ No new papers to process.")
        return

    print(f"--> Initializing pipeline for {CONFIG['MODEL_NAME']} on device_map='auto'...")
    try:
        # Load the model directly using HuggingFace's pipeline abstraction
        generator = pipeline(
            "text-generation",
            model=CONFIG['MODEL_NAME'],
            model_kwargs={"torch_dtype": torch.bfloat16},
            device_map="auto",
            token=hf_token
        )
    except Exception as e:
        print(f"❌ Error initializing HuggingFace pipeline: {e}")
        return

    print(f"Total papers to process: {len(papers_to_process)}")

    # Process sequentially to enforce strict JSON generation cleanly
    for pid, p_data in tqdm(papers_to_process.items(), desc="Processing HuggingFace NER"):
        try:
            messages = [
                {"role": "system", "content": "You are a data extraction system. You only output valid JSON. You never output conversational text."},
                {"role": "user", "content": generate_prompt(pid, p_data['abstract'])}
            ]

            # Generate output via the pipeline Chat Template
            outputs = generator(
                messages,
                max_new_tokens=1500,
                temperature=0.1,
                do_sample=True,
                return_full_text=False # Return only the assistant's generated response
            )

            raw_text = outputs[0]['generated_text']
            json_text = extract_json_from_text(raw_text)
            
            # Validation via Pydantic schema
            validated_data = BatchNERResult.model_validate_json(json_text)
            
            for paper_result in validated_data.results:
                if paper_result.paper_id == pid:
                    annotated_papers[pid] = {
                        "abstract": p_data['abstract'],
                        "entities": [e.model_dump() for e in paper_result.entities],
                        "title": p_data.get('title', ""),
                        "date": p_data.get('date', "")
                    }
                    
        except Exception as e:
            print(f"\nError on paper {pid}: {e}")
        
        # Save checkpoints dynamically to prevent data loss on OOM/crash
        if len(annotated_papers) % 50 == 0:
            with open(CONFIG['OUTPUT_FILE'], 'w', encoding='utf-8') as f:
                json.dump(annotated_papers, f, indent=4, ensure_ascii=False)

    # Final save
    with open(CONFIG['OUTPUT_FILE'], 'w', encoding='utf-8') as f:
        json.dump(annotated_papers, f, indent=4, ensure_ascii=False)
    
    print(f"\n✅ Finished! Saved {len(annotated_papers)} annotations.")

if __name__ == "__main__":
    main()